### ISSUE TITLE
undefined: secp256k1.VerifySignature

### ISSUE THREAD

**Issue by Cyncra** [InjectiveLabs/sdk-go#191]
Hello, I download sdk-go and run example.go
# github.com/InjectiveLabs/sdk-go/chain/crypto/ethsecp256k1
chain\crypto\ethsecp256k1\ethsecp256k1.go:204:19: undefined: secp256k1.VerifySignature
The error keeps happening. Is there a solution?

**Comment by vinhphuctadang** [comment]
Hey, please run `go mod tidy`

**Comment by nikhilsaraf** [comment]
this issue still exists when cross-compiling on macos for linux, fyi @vinhphuctadang 

```
$ GOOS=linux GOARCH=amd64 go build ./...
# github.com/InjectiveLabs/sdk-go/chain/crypto/ethsecp256k1
chain/crypto/ethsecp256k1/ethsecp256k1.go:204:19: undefined: secp256k1.VerifySignature
```

it works for me when I just run `go build ./...`
