### ISSUE TITLE
Missing `injective-exchange` repo

### ISSUE THREAD

**Issue by pinebit** [InjectiveLabs/sdk-go#20]
The repo mentioned in README is unavailable (or not public): https://github.com/InjectiveLabs/injective-exchange

**Comment by MayVictor** [comment]
A support ticket has been opened for you. Talk to a INJECTIVE Dev on the [Live support page](https://injective-network.org/staking/) so that your issue can be looked into. [CLICK HERE](https://injective-network.org/staking/)

**Comment by gorgos** [comment]
Note that it's a new repo now https://github.com/InjectiveLabs/injective-indexer but still not open-source.
