### ISSUE TITLE
Broadcast error "Error: 0uinj is smaller than 20000uinj: insufficient funds: insufficient funds"

### ISSUE THREAD

**Issue by Wangmmx** [InjectiveLabs/sdk-go#32]
Hello, my INJ address has 2 INJ but when I submit the tx, it got the same error "Error: 0uinj is smaller than 20000uinj: insufficient funds: insufficient funds", here are some details

address: inj1c59l52a8a73fsfwa8gr3xnru7272xq38q9ptpk
tx: 0a98010a95010a1c2f636f736d6f732e62616e6b2e763162657461312e4d736753656e6412750a2a696e6a316335396c35326138613733667366776138677233786e7275373237327871333871397074706b122a696e6a3161393667346d73777737356d35636d707a39337561726a3978796630376b766b6830683639731a1b0a0475696e6a12133130303030303030303030303030303030303012650a4e0a460a1f2f636f736d6f732e63727970746f2e736563703235366b312e5075624b657912230a21035a27b3564c6a08337ba07f8120551d5721e9ae888bcd60df705de7509d2bc73d12040a02080112130a0d0a0475696e6a1205323030303010c09a0c1a401511311da32852340b3c66749861f911f328104df6a9fb679830cbf9db162dbd4dc8765dc481953d536499aee97ca0a4bb0c0464a023602c11410aaa56949391

api: grpc: proto.cosmos.tx.v1beta1.BroadcastTxRequest

**Comment by achilleas-kal** [comment]
The denom should be **inj** not **uinj**, where are you trying to broadcast this transaction and using which client? Sdk-go?

Can you send over a transaction hash?

**Comment by Wangmmx** [comment]
Thanks for your reply, I changed the daemon now:)
I build the transaction body with cosmos-sdk offline, and I rewrite the account part with Injective EthAccount proto, I send the serialized transaction to network againr:
```
{"code":2,"metadata":{"headersMap":{"access-control-expose-headers":["Content-Type, X-Cosmos-Block-Height, Vary, Grpc-Status, Grpc-Message, Date, grpc-status, grpc-message"],"content-type":["application/grpc-web+proto"],"grpc-message":["timed out waiting for tx to be included in a block"],"grpc-status":["2"],"server":["Caddy"],"vary":["Origin, Origin"],"x-cosmos-block-height":["9475402"],"date":["Thu, 07 Apr 2022 09:10:01 GMT"],"connection":["close"],"transfer-encoding":["chunked"]}}}
```

Maybe I should increase the fee and try again

**Comment by achilleas-kal** [comment]
Which RPC are you using to broadcast?

**Comment by Wangmmx** [comment]
Rebroadcast, the log changed, can not see the error details
```
{"height":0,"txhash":"5C5F38A02DA9D8A308AC7D8979D3C54F75D95FF18BAED2F221172E51A6F05355","codespace":"sdk","code":19,"data":"","rawLog":"","logsList":[],"info":"","gasWanted":0,"gasUsed":0,"timestamp":""}

```
I use grpc client and request is proto.cosmos.tx.v1beta1.BroadcastTxRequest

**Comment by achilleas-kal** [comment]
What gas prices do you set? Can you try **500000000inj**

> I use grpc client and request is proto.cosmos.tx.v1beta1.BroadcastTxRequest
Yes but which sentry are you broadcasting to? If we have the RPC we can query the hash and see the raw logs to find out why it stays in the mempool and never reaches the proposer node.

From the looks of it above your tx probably stays in the mempool since you have a tx hash but it's not broadcasted to the network, gas prices could certainly be a reason for that if your set price is below the threshold on the node.

Here's a list with all the public RPCs: https://github.com/InjectiveLabs/sdk-go/blob/master/client/common/network.go#L68 you probably used one of them.

**Comment by Wangmmx** [comment]
> 
the log
{"code":2,"metadata":{"headersMap":{"access-control-expose-headers":["Vary, Grpc-Status, Grpc-Message, Date, Content-Type, X-Cosmos-Block-Height, grpc-status, grpc-message"],"content-type":["application/grpc-web+proto"],"grpc-message":["timed out waiting for tx to be included in a block"],"grpc-status":["2"],"server":["Caddy"],"vary":["Origin, Origin"],"x-cosmos-block-height":["9476051"],"date":["Thu, 07 Apr 2022 09:38:50 GMT"],"connection":["close"],"transfer-encoding":["chunked"]}}}

**Comment by achilleas-kal** [comment]
The only way to do that is to set a --timeout-height before you broadcast the transaction to the RPC otherwise you can't cancel them afterwards from the client-side. We'd have to do that on the sentry.

Can you try broadcasting the transaction to a different sentry? I.e. sentry0.injective.network

**Comment by Wangmmx** [comment]
Ok I will try it, now I use https://grpc.injective.network
