### ISSUE TITLE
Can I use lcd api for block?

### ISSUE THREAD

**Issue by Wangmmx** [InjectiveLabs/sdk-go#33]
Hi, I used the cosmos lcd api to get the block details , but in Injective, those api can not work:https://lcd.injective.network/blocks/latest

```
{"error":"Unregistered interface types.Evidence"}

```
Can I use the same api with other endpoint or I should change the api?

**Comment by achilleas-kal** [comment]
Hey, here's the endpoint you're looking for: https://lcd.injective.network/cosmos/base/tendermint/v1beta1/blocks/latest

You can take a look in Swagger for chain queries: https://lcd.injective.network/swagger/#/

**Comment by Wangmmx** [comment]
> Hey, here's the endpoint you're looking for: https://lcd.injective.network/cosmos/base/tendermint/v1beta1/blocks/latest
> 
> You can take a look in Swagger for chain queries: https://lcd.injective.network/swagger/#/

Thanks a lot!
