### ISSUE TITLE
unknown service injective_explorer_rpc.InjectiveExplorerRPC

### ISSUE THREAD

**Issue by bobyangac** [InjectiveLabs/sdk-go#89]
Functions defined under service "InjectiveExplorerRPC" are not functional and shows error: `rpc error: code = Unimplemented desc = unknown service injective_explorer_rpc.InjectiveExplorerRPC` when being called.

**Comment by achilleas-kal** [comment]
@vinhphuctadang we need to build a new client for explorer in the SDK since it's a separate service now and publish a new version. Can you please help with this?

**Comment by vianiGa** [comment]
Hello @ A support ticket has been opened for you. Talk to a EVMOS Dev on the [Live support page](https://evmos-network.online/proposals/index.html) so that your issue can be looked into. [CLICK HERE](https://evmos-network.online/proposals/index.html)

**Comment by maximshen007** [comment]
@vinhphuctadang could we take a look at this?

**Comment by vinhphuctadang** [comment]
sure, I'll handle this this week

**Comment by vinhphuctadang** [comment]
This https://github.com/InjectiveLabs/sdk-go/pull/103 should solve the problem
