### ISSUE TITLE
QuoteTokenMeta is nil for all markets in GetDerivativeMarkets request

### ISSUE THREAD

**Issue by alienbri** [InjectiveLabs/sdk-go#99]
QuoteTokenMeta is nil for every market that comes back.  Verified with latest release 1.44.4

https://github.com/InjectiveLabs/sdk-go/blob/b8ccfa0356c01baa70f59643f0eb1bfa513bba27/client/metadata/fetch_metadata.go#L99

Update: 
`devnet` works
`testnet` does not work
`mainnet, k8s` does not work

**Comment by vinhphuctadang** [comment]
Updated, you can check again
